name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20.x] # Add 18.x here only if you truly support it
    env:
      CI: true
      NODE_OPTIONS: --no-deprecation
      NEXT_TELEMETRY_DISABLED: 1
      APP_MODE: mock # keep tests hermetic; no Stripe/Firebase in CI
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - run: npm ci
      - run: npm run type-check
      - run: npm test -- --ci
      - run: npm run build

  # Make security non-blocking until you want it strict
  security:
    runs-on: ubuntu-latest
    continue-on-error: true # flip to false when you're ready to gate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm ci
      # You can scope this to critical only if you prefer:
      - run: npm audit --audit-level=critical
